"""updated models

Revision ID: 5368967306a3
Revises: a8d9a648bd2c
Create Date: 2023-04-11 22:30:35.473868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5368967306a3'
down_revision = 'a8d9a648bd2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('units', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'units')
    # ### end Alembic commands ###
