"""add recipemodel in schemas

Revision ID: d8f75ef04ee5
Revises: 14db800121db
Create Date: 2023-04-14 19:51:48.500529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f75ef04ee5'
down_revision = '14db800121db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
